### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by alanzhai219** [artyom-beilis/dlprimitives#32]
- error log
CMakeFiles/dlprim_onnx.dir/build.make:73: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:488: CMakeFiles/dlprim_onnx.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
- clinfo
Intel(R) UHD Graphics 630

**Comment by artyom-beilis** [comment]
Can you give full build output?

From cmake to make

**Comment by artyom-beilis** [comment]
It looks some cmake/make generation issue. I have no idea where it comes from.

Try using ninga. i.e.

    cmake -G Ninja ..
    ninja

Instead of GNU Make.
